//! Built-in reference pages served at `/help` and the starter template used
//! by `slides init`.
//!
//! Content lives in three markdown files at the repo root:
//! - `SYNTAX.md` — authoring syntax reference (single source of truth)
//! - `USAGE.md` — keyboard shortcuts and CLI commands
//! - `templates/init.md` — starter deck written by `slides init`
//!
//! All three are embedded into the binary at compile time via `include_str!`.

use crate::parser::markdown::render_plain;

/// The starter template generated by `slides init`.
pub const INIT_TEMPLATE: &str = include_str!("../templates/init.md");

/// Authoring syntax reference, also exposed raw at `/syntax.md`.
pub const SYNTAX_MD: &str = include_str!("../SYNTAX.md");

/// Keyboard shortcuts and CLI commands.
const USAGE_MD: &str = include_str!("../USAGE.md");

/// Generate the help page HTML, rendered from SYNTAX.md and USAGE.md.
pub fn help_html() -> String {
    let syntax_html = render_plain(SYNTAX_MD);
    let usage_html = render_plain(USAGE_MD);

    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>slides — Reference</title>
  <style>{css}</style>
</head>
<body>
  <div class="help">
    <nav>
      <a href="#syntax">Syntax</a>
      <a href="#usage">Usage</a>
      <a href="/syntax.md">Raw SYNTAX.md</a>
    </nav>
    <main>
      <section id="syntax">
{syntax}
      </section>
      <section id="usage">
{usage}
      </section>
    </main>
    <footer>
      <p>This page is rendered from <code>SYNTAX.md</code> and <code>USAGE.md</code> at the repo root. The raw syntax source is available at <code>/syntax.md</code>.</p>
    </footer>
  </div>
</body>
</html>"##,
        css = HELP_CSS,
        syntax = syntax_html,
        usage = usage_html,
    )
}

const HELP_CSS: &str = r#"
* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  background: #0f172a;
  color: #e2e8f0;
  line-height: 1.7;
}

.help {
  max-width: 52rem;
  margin: 0 auto;
  padding: 3rem 2rem 4rem;
}

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 2.5rem;
  padding: 1rem;
  background: #1e293b;
  border-radius: 8px;
}

nav a {
  color: #7dd3fc;
  text-decoration: none;
  padding: 0.25rem 0.75rem;
  border-radius: 4px;
  font-size: 0.9rem;
}

nav a:hover {
  background: #334155;
}

section {
  margin-bottom: 3rem;
}

h1 {
  font-size: 2rem;
  font-weight: 700;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid #1e293b;
  color: #f1f5f9;
}

h2 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-top: 2rem;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid #1e293b;
  color: #f1f5f9;
}

h3 {
  font-size: 1.1rem;
  font-weight: 600;
  margin-top: 1.5rem;
  margin-bottom: 0.75rem;
  color: #cbd5e1;
}

p {
  margin-bottom: 0.75rem;
  color: #cbd5e1;
}

ul, ol {
  margin-bottom: 0.75rem;
  margin-left: 1.5rem;
  color: #cbd5e1;
}

li {
  margin-bottom: 0.25rem;
}

hr {
  border: none;
  border-top: 1px solid #1e293b;
  margin: 2rem 0;
}

pre {
  background: #1e293b;
  border: 1px solid #334155;
  border-radius: 8px;
  padding: 1rem 1.25rem;
  overflow-x: auto;
  margin-bottom: 1rem;
  font-size: 0.875rem;
  line-height: 1.6;
}

code {
  font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.875em;
}

p code, td code, li code, th code {
  background: #1e293b;
  padding: 0.15em 0.4em;
  border-radius: 3px;
  color: #7dd3fc;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 1rem;
}

thead {
  background: #1e293b;
}

th {
  text-align: left;
  padding: 0.6rem 1rem;
  color: #f1f5f9;
  font-weight: 600;
  border-bottom: 1px solid #334155;
}

tr {
  border-bottom: 1px solid #1e293b;
}

td {
  padding: 0.6rem 1rem;
  color: #cbd5e1;
  vertical-align: top;
}

blockquote {
  border-left: 3px solid #334155;
  padding: 0.5rem 1rem;
  margin: 1rem 0;
  color: #94a3b8;
}

a {
  color: #7dd3fc;
}

kbd {
  background: #334155;
  border: 1px solid #475569;
  border-radius: 4px;
  padding: 0.1em 0.4em;
  font-family: inherit;
  font-size: 0.85em;
}

footer {
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 1px solid #1e293b;
  color: #64748b;
  font-size: 0.9rem;
}
"#;
