/// Built-in syntax reference, served at /help and used by `slides init`.

/// The starter template generated by `slides init`.
pub const INIT_TEMPLATE: &str = r#"---
title: My Presentation
theme: minimal
aspect: "16:9"
transition: slide
color_scheme: light
# highlight_theme: github
# auto_fit: warn
# export_images: relative
---

# My Presentation

Subtitle or tagline here

^[These are inline speaker notes — only visible in presenter mode.]

---

## Basic Slide

Regular markdown works as expected:

- **Bold text** and *italic text*
- ~~Strikethrough~~ for deletions
- `inline code` for technical terms
- [Links](https://example.com) work too

---

## Code Blocks

```rust
fn main() {
    println!("Syntax highlighting works out of the box.");
}
```

```python
def greet(name: str) -> str:
    return f"Hello, {name}!"
```

---

## Tables

| Feature       | Status |
|---------------|--------|
| Markdown      | Done   |
| Layouts       | Done   |
| Speaker Notes | Done   |
| Export         | Done   |

---

## Task Lists

- [x] Write the slides
- [x] Add speaker notes
- [ ] Rehearse the talk
- [ ] Deliver with confidence

---

## Blockquotes

> "The best way to predict the future is to invent it."
> — Alan Kay

Footnotes work too[^1].

[^1]: This appears at the bottom of the slide.

--- {transition: fade}

## Transitions

This slide used `--- {transition: fade}` as its separator.

You can also set `class` and `timing` on separators:

```markdown
--- {transition: fade, class: centered, timing: 45s}
```

--- {class: centered}

## Semantic Annotations

Add classes to any block with trailing `{.classname}` syntax:

This paragraph has emphasis styling. {.emphasis}

> This blockquote is a callout. {.callout}

This is supplementary context. {.aside}

---

## Fragment Reveals

Fragments appear one at a time when you press next:

- First point {.fragment}
- Second point {.fragment}
- Third point {.fragment}

Press → to reveal each fragment before advancing.

---

:::split 60/40

## Split Layout

Use `:::split` to create columns. This is a 60/40 split — content on the left, sidebar on the right.

Separate regions with `+++`.

+++

### Sidebar

- Supporting detail
- Extra context
- Related links

:::

---

:::split

## Even Split

Omit the ratio for a default 50/50 split.

+++

## Right Column

Both sides get equal space.

:::

---

:::split 33/34/33

### Left

Three-way splits work too.

+++

### Center

Use any number of regions.

+++

### Right

Just match the ratios.

:::

---

:::grid 2x2

### Fast

Hot reload in milliseconds.

+++

### Simple

One markdown file is all you need.

+++

### Portable

Single binary, no dependencies.

+++

### Beautiful

Clean defaults, customizable themes.

:::

---

:::stack

## Stacked Layout

`:::stack` arranges regions vertically with equal spacing.

+++

This is the second region in the stack.

+++

And this is the third.

:::

---

:::notes
These are block speaker notes.

They can span multiple lines and contain **markdown** formatting.

Use these for detailed talking points that you don't want the audience to see.
:::

## Speaker Notes

Two ways to add notes:

1. **Inline:** `^[Your note here]` — embedded in content
2. **Block:** `:::notes ... :::` — a dedicated notes section

^[This is an inline note attached to this slide.]

---

## Keyboard Shortcuts

| Key             | Action              |
|-----------------|---------------------|
| → ↓ Space PgDn  | Next slide/fragment |
| ← ↑ PgUp        | Previous            |
| Home             | First slide         |
| End              | Last slide          |
| F                | Toggle fullscreen   |
| D                | Toggle dark mode    |
| Esc              | Exit fullscreen     |

---

## Commands

```bash
# Live preview with hot reload
slides serve deck.md

# Export to static HTML
slides export deck.md -f html -o output.html

# Export to PDF (requires --features pdf)
slides export deck.md -f pdf -o output.pdf

# Presenter mode with notes & timer
slides present deck.md
```

---

## Get Started

1. Edit this file
2. Run `slides serve presentation.md`
3. Start presenting

That's it.
"#;

/// Generate the help page HTML, styled as a presentation itself.
pub fn help_html() -> String {
    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>slides — Syntax Reference</title>
  <style>{css}</style>
</head>
<body>
  <div class="help">
    <header>
      <h1>slides — Syntax Reference</h1>
      <p class="subtitle">Everything you can do in a <code>.md</code> presentation file</p>
    </header>
    <nav>
      <a href="#frontmatter">Frontmatter</a>
      <a href="#slides">Slides</a>
      <a href="#markdown">Markdown</a>
      <a href="#annotations">Annotations</a>
      <a href="#layouts">Layouts</a>
      <a href="#notes">Speaker Notes</a>
      <a href="#keyboard">Keyboard</a>
      <a href="#cli">CLI</a>
    </nav>
    <main>

      <section id="frontmatter">
        <h2>Frontmatter</h2>
        <p>Configure your deck with YAML at the top of the file:</p>
        <pre><code>---
title: My Presentation
theme: minimal           # minimal | dark
aspect: "16:9"           # "16:9" | "4:3"
transition: slide        # slide | fade
color_scheme: light      # light | dark
highlight_theme: github  # syntax highlight theme
auto_fit: warn           # warn | shrink
export_images: relative  # relative | inline
---</code></pre>
        <p>All fields are optional. Sensible defaults are used when omitted.</p>
      </section>

      <section id="slides">
        <h2>Slide Separators</h2>
        <p>Separate slides with <code>---</code> on its own line:</p>
        <pre><code># First Slide

Content here.

---

# Second Slide

More content.</code></pre>

        <h3>Separator Attributes</h3>
        <p>Add per-slide attributes in curly braces after the separator:</p>
        <pre><code>--- {{transition: fade}}
--- {{class: centered}}
--- {{timing: 45s}}
--- {{transition: fade, class: centered, timing: 30s}}</code></pre>
      </section>

      <section id="markdown">
        <h2>Markdown Features</h2>
        <p>Standard markdown plus these extensions:</p>

        <div class="feature-grid">
          <div class="feature">
            <h3>Text Formatting</h3>
            <pre><code>**bold**  *italic*  ~~strikethrough~~
`inline code`  [links](url)</code></pre>
          </div>

          <div class="feature">
            <h3>Code Blocks</h3>
            <pre><code>```rust
fn main() {{
    println!("highlighted!");
}}
```</code></pre>
          </div>

          <div class="feature">
            <h3>Tables</h3>
            <pre><code>| Column A | Column B |
|----------|----------|
| Cell 1   | Cell 2   |</code></pre>
          </div>

          <div class="feature">
            <h3>Task Lists</h3>
            <pre><code>- [x] Completed item
- [ ] Pending item</code></pre>
          </div>

          <div class="feature">
            <h3>Footnotes</h3>
            <pre><code>Text with a footnote[^1].

[^1]: The footnote content.</code></pre>
          </div>

          <div class="feature">
            <h3>Blockquotes</h3>
            <pre><code>&gt; "Quoted text here."
&gt; — Attribution</code></pre>
          </div>
        </div>
      </section>

      <section id="annotations">
        <h2>Semantic Annotations</h2>
        <p>Add CSS classes to any block element with trailing <code>{{.classname}}</code>:</p>
        <pre><code>This paragraph is emphasized. {{.emphasis}}

&gt; This is styled as a callout. {{.callout}}

This is secondary text. {{.aside}}

- Appears on next press {{.fragment}}
- Also revealed step-by-step {{.fragment}}</code></pre>
        <p>Multiple classes: <code>{{.callout .warning}}</code></p>

        <h3>Built-in Classes</h3>
        <table>
          <tr><td><code>.fragment</code></td><td>Revealed one-by-one on keypress</td></tr>
          <tr><td><code>.emphasis</code></td><td>Visual emphasis (theme-dependent)</td></tr>
          <tr><td><code>.callout</code></td><td>Highlighted callout block</td></tr>
          <tr><td><code>.aside</code></td><td>De-emphasized secondary text</td></tr>
        </table>
      </section>

      <section id="layouts">
        <h2>Layout Directives</h2>
        <p>Use <code>:::</code> directives to create multi-region layouts. Separate regions with <code>+++</code>.</p>

        <h3>Split (Columns)</h3>
        <pre><code>:::split 60/40

Left column content (60% width).

+++

Right column content (40% width).

:::</code></pre>
        <p>Omit the ratio for 50/50. Use three or more values for multi-column: <code>:::split 33/34/33</code></p>

        <h3>Grid</h3>
        <pre><code>:::grid 2x2

Top-left cell.

+++

Top-right cell.

+++

Bottom-left cell.

+++

Bottom-right cell.

:::</code></pre>
        <p>Format: <code>:::grid COLSxROWS</code></p>

        <h3>Stack (Vertical)</h3>
        <pre><code>:::stack

First region.

+++

Second region.

+++

Third region.

:::</code></pre>
        <p>Arranges regions vertically with equal spacing.</p>
      </section>

      <section id="notes">
        <h2>Speaker Notes</h2>
        <p>Notes are visible only in presenter mode (<code>slides present</code>).</p>

        <h3>Block Notes</h3>
        <pre><code>:::notes
Detailed talking points go here.
Supports **markdown** formatting.
:::</code></pre>

        <h3>Inline Notes</h3>
        <pre><code>Visible content ^[This note is hidden from the audience.]</code></pre>
        <p>Inline notes are stripped from the rendered slide and collected into the notes panel.</p>
      </section>

      <section id="keyboard">
        <h2>Keyboard Shortcuts</h2>
        <table>
          <tr><td><kbd>→</kbd> <kbd>↓</kbd> <kbd>Space</kbd> <kbd>PgDn</kbd></td><td>Next slide or fragment</td></tr>
          <tr><td><kbd>←</kbd> <kbd>↑</kbd> <kbd>PgUp</kbd></td><td>Previous slide or fragment</td></tr>
          <tr><td><kbd>Home</kbd></td><td>First slide</td></tr>
          <tr><td><kbd>End</kbd></td><td>Last slide</td></tr>
          <tr><td><kbd>F</kbd></td><td>Toggle fullscreen</td></tr>
          <tr><td><kbd>D</kbd></td><td>Toggle dark mode</td></tr>
          <tr><td><kbd>Esc</kbd></td><td>Exit fullscreen</td></tr>
        </table>
        <p>Touch: swipe left/right to navigate.</p>
      </section>

      <section id="cli">
        <h2>CLI Commands</h2>
        <pre><code># Create a new presentation from template
slides init

# Live preview with hot reload
slides serve deck.md
slides serve deck.md --port 8080

# Export to static HTML
slides export deck.md -f html -o output.html

# Export to PDF (requires --features pdf)
slides export deck.md -f pdf -o output.pdf

# Presenter mode with notes, timer, and progress
slides present deck.md</code></pre>
      </section>

    </main>
    <footer>
      <p>This page is always available at <code>/help</code> when running <code>slides serve</code> or <code>slides present</code>.</p>
    </footer>
  </div>
</body>
</html>"##,
        css = HELP_CSS,
    )
}

const HELP_CSS: &str = r#"
* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  background: #0f172a;
  color: #e2e8f0;
  line-height: 1.7;
}

.help {
  max-width: 52rem;
  margin: 0 auto;
  padding: 3rem 2rem 4rem;
}

header {
  margin-bottom: 2rem;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid #1e293b;
}

header h1 {
  font-size: 2rem;
  font-weight: 700;
  letter-spacing: -0.02em;
}

.subtitle {
  color: #94a3b8;
  margin-top: 0.5rem;
  font-size: 1.1rem;
}

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 2.5rem;
  padding: 1rem;
  background: #1e293b;
  border-radius: 8px;
}

nav a {
  color: #7dd3fc;
  text-decoration: none;
  padding: 0.25rem 0.75rem;
  border-radius: 4px;
  font-size: 0.9rem;
}

nav a:hover {
  background: #334155;
}

section {
  margin-bottom: 3rem;
}

h2 {
  font-size: 1.5rem;
  font-weight: 700;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid #1e293b;
  color: #f1f5f9;
}

h3 {
  font-size: 1.1rem;
  font-weight: 600;
  margin-top: 1.5rem;
  margin-bottom: 0.75rem;
  color: #cbd5e1;
}

p {
  margin-bottom: 0.75rem;
  color: #cbd5e1;
}

pre {
  background: #1e293b;
  border: 1px solid #334155;
  border-radius: 8px;
  padding: 1rem 1.25rem;
  overflow-x: auto;
  margin-bottom: 1rem;
  font-size: 0.875rem;
  line-height: 1.6;
}

code {
  font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.875em;
}

p code, td code, li code {
  background: #1e293b;
  padding: 0.15em 0.4em;
  border-radius: 3px;
  color: #7dd3fc;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 1rem;
}

tr {
  border-bottom: 1px solid #1e293b;
}

td {
  padding: 0.6rem 1rem;
  color: #cbd5e1;
}

td:first-child {
  white-space: nowrap;
}

kbd {
  background: #334155;
  border: 1px solid #475569;
  border-radius: 4px;
  padding: 0.1em 0.4em;
  font-family: inherit;
  font-size: 0.85em;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr));
  gap: 1rem;
  margin-top: 1rem;
}

.feature {
  background: #1e293b;
  border-radius: 8px;
  padding: 1.25rem;
  border: 1px solid #334155;
}

.feature h3 {
  margin-top: 0;
  margin-bottom: 0.5rem;
  color: #f1f5f9;
}

.feature pre {
  border: none;
  background: #0f172a;
  margin-bottom: 0;
}

footer {
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 1px solid #1e293b;
  color: #64748b;
  font-size: 0.9rem;
}
"#;
